FROM node:21-alpine AS development
ENV NODE_ENV development

ARG REACT_APP_API_ADDRESS

ENV REACT_APP_API_ADDRESS $REACT_APP_API_ADDRESS
# Add a work directory
WORKDIR /app

# Cache and Install dependencies
COPY package.json .

#RUN yarn install
RUN npm i

# Copy app files
COPY . .

# Expose port
EXPOSE 3000

# Start the app
CMD [ "npm", "start" ]
